#!/bin/bash

# Update package lists
apt-get update

# Install Nginx
apt-get -y install nginx

# Allow HTTP traffic
ufw allow 'Nginx HTTP'

# Create HTML directory and index file
mkdir -p /var/www/html
echo 'Hello World!' > /var/www/html/index.html

# Define Nginx server configuration
SERVER_CONFIG="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}"

# Replace default Nginx configuration with custom configuration
sed -i '/^server {/,$d' /etc/nginx/sites-enabled/default
echo "$SERVER_CONFIG" > /etc/nginx/sites-enabled/default

# Restart Nginx service
service nginx restart
