#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get -y update
apt-get install -y haproxy=2.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# listen to web01 and web02
echo "
    listen load_balancer
    bind *:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 527523-web-01 54.165.237.218:80 check
    server 527523-web-02 35.168.7.176:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start